language: c

#os:
#  - linux
#  - osx

compiler:
  - gcc
  - clang

install:
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then sudo brew tap homebrew/science; brew update; fi
#  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install -y libgsl0-dev libhdf5-serial-dev; fi
#  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gsl hdf5; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev libhdf5-serial-dev

script: ./autogen.sh --verbose && ./configure && make

notifications:
  email:
    on_success: change
    on_failure: always
